### ISSUE TITLE
Tracking issue for release notes of #142: test

### ISSUE THREAD

**Issue by ehuss** [ehuss/triagebot-test#143]
This issue tracks the release notes text for #142.

- [ ] Issue is nominated for the responsible team (and T-release nomination is removed).
- [ ] Proposed text is drafted by team responsible for underlying change.
- [ ] Issue is nominated for release team review of clarity for wider audience.
- [ ] Release team includes text in release notes/blog posts.

Release notes text:

The section title will be de-duplicated by the release team with other release notes issues.
Prefer to use the standard titles from [previous releases](https://doc.rust-lang.org/nightly/releases.html).
More than one section can be included if needed.

```markdown
# Compatibility Notes
- [test](https://github.com/ehuss/triagebot-test/pull/142)
```

Release blog section (if any, leave blank if no section is expected):

```markdown
```
